### ISSUE TITLE
[Bug] MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### ISSUE THREAD

**Issue by pure-wei** [open-mmlab/mmocr#2024]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

python 3.11.5 pytorch 2.1.2 cuda 12.1

### Reproduces the problem - code sample

!pip install -U openmim
!pip install opencv-python pillow matplotlib seaborn tqdm -i https://pypi.tuna.tsinghua.edu.cn/simple
!git clone https://github.com/open-mmlab/mmocr.git
!mim install -e .
import mmocr

print(dir(mmocr))
print(dir(mmcv))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], [line 2](vscode-notebook-cell:?execution_count=7&line=2)
      [1](vscode-notebook-cell:?execution_count=7&line=1) # 检查 mmocr
----> [2](vscode-notebook-cell:?execution_count=7&line=2) import mmocr
      [3](vscode-notebook-cell:?execution_count=7&line=3) #print('mmocr版本', mmocr.__version__)
      [4](vscode-notebook-cell:?execution_count=7&line=4) print(dir(mmocr))

File [c:\Users\rhwto\Desktop\code\github\MMOCR_tutorials-main\20230620\mmocr\mmocr\__init__.py:4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4)
      [1](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:1) # Copyright (c) OpenMMLab. All rights reserved.
      [3](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:3) import mmcv
----> [4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4) import mmdet
      [6](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:6) try:
      [7](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:7)     import mmengine

File [c:\Users\rhwto\anaconda3\Lib\site-packages\mmdet\__init__.py:17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)
     [13](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:13) mmengine_maximum_version = '1.0.0'
     [14](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:14) mmengine_version = digit_version(mmengine.__version__)
     [16](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:16) assert (mmcv_version >= digit_version(mmcv_minimum_version)
---> [17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)         and mmcv_version < digit_version(mmcv_maximum_version)), \
     [18](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:18)     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     [19](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:19)     f'Please install mmcv>={mmcv_minimum_version}, <{mmcv_maximum_version}.'
     [21](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:21) assert (mmengine_version >= digit_version(mmengine_minimum_version)
     [22](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:22)         and mmengine_version < digit_version(mmengine_maximum_version)), \
     [23](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:23)     f'MMEngine=={mmengine.__version__} is used but incompatible. ' \
     [24](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:24)     f'Please install mmengine>={mmengine_minimum_version}, ' \
     [25](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:25)     f'<{mmengine_maximum_version}.'
     [27](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:27) __all__ = ['__version__', 'version_info', 'digit_version']

AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### Reproduces the problem - command or script

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], [line 2](vscode-notebook-cell:?execution_count=7&line=2)
      [1](vscode-notebook-cell:?execution_count=7&line=1) # 检查 mmocr
----> [2](vscode-notebook-cell:?execution_count=7&line=2) import mmocr
      [3](vscode-notebook-cell:?execution_count=7&line=3) #print('mmocr版本', mmocr.__version__)
      [4](vscode-notebook-cell:?execution_count=7&line=4) print(dir(mmocr))

File [c:\Users\rhwto\Desktop\code\github\MMOCR_tutorials-main\20230620\mmocr\mmocr\__init__.py:4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4)
      [1](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:1) # Copyright (c) OpenMMLab. All rights reserved.
      [3](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:3) import mmcv
----> [4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4) import mmdet
      [6](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:6) try:
      [7](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:7)     import mmengine

File [c:\Users\rhwto\anaconda3\Lib\site-packages\mmdet\__init__.py:17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)
     [13](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:13) mmengine_maximum_version = '1.0.0'
     [14](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:14) mmengine_version = digit_version(mmengine.__version__)
     [16](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:16) assert (mmcv_version >= digit_version(mmcv_minimum_version)
---> [17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)         and mmcv_version < digit_version(mmcv_maximum_version)), \
     [18](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:18)     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     [19](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:19)     f'Please install mmcv>={mmcv_minimum_version}, <{mmcv_maximum_version}.'
     [21](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:21) assert (mmengine_version >= digit_version(mmengine_minimum_version)
     [22](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:22)         and mmengine_version < digit_version(mmengine_maximum_version)), \
     [23](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:23)     f'MMEngine=={mmengine.__version__} is used but incompatible. ' \
     [24](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:24)     f'Please install mmengine>={mmengine_minimum_version}, ' \
     [25](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:25)     f'<{mmengine_maximum_version}.'
     [27](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:27) __all__ = ['__version__', 'version_info', 'digit_version']

AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### Reproduces the problem - error message

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], [line 2](vscode-notebook-cell:?execution_count=7&line=2)
      [1](vscode-notebook-cell:?execution_count=7&line=1) # 检查 mmocr
----> [2](vscode-notebook-cell:?execution_count=7&line=2) import mmocr
      [3](vscode-notebook-cell:?execution_count=7&line=3) #print('mmocr版本', mmocr.__version__)
      [4](vscode-notebook-cell:?execution_count=7&line=4) print(dir(mmocr))

File [c:\Users\rhwto\Desktop\code\github\MMOCR_tutorials-main\20230620\mmocr\mmocr\__init__.py:4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4)
      [1](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:1) # Copyright (c) OpenMMLab. All rights reserved.
      [3](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:3) import mmcv
----> [4](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:4) import mmdet
      [6](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:6) try:
      [7](file:///C:/Users/rhwto/Desktop/code/github/MMOCR_tutorials-main/20230620/mmocr/mmocr/__init__.py:7)     import mmengine

File [c:\Users\rhwto\anaconda3\Lib\site-packages\mmdet\__init__.py:17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)
     [13](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:13) mmengine_maximum_version = '1.0.0'
     [14](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:14) mmengine_version = digit_version(mmengine.__version__)
     [16](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:16) assert (mmcv_version >= digit_version(mmcv_minimum_version)
---> [17](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:17)         and mmcv_version < digit_version(mmcv_maximum_version)), \
     [18](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:18)     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     [19](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:19)     f'Please install mmcv>={mmcv_minimum_version}, <{mmcv_maximum_version}.'
     [21](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:21) assert (mmengine_version >= digit_version(mmengine_minimum_version)
     [22](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:22)         and mmengine_version < digit_version(mmengine_maximum_version)), \
     [23](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:23)     f'MMEngine=={mmengine.__version__} is used but incompatible. ' \
     [24](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:24)     f'Please install mmengine>={mmengine_minimum_version}, ' \
     [25](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:25)     f'<{mmengine_maximum_version}.'
     [27](file:///C:/Users/rhwto/anaconda3/Lib/site-packages/mmdet/__init__.py:27) __all__ = ['__version__', 'version_info', 'digit_version']

AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

### Additional information

please fix the error with cuda file,and i can't find the preciously compatible version that works

**Comment by yechaoying** [comment]
I uninstalled mmcv==2.1.0 and installed mmcv==2.0.0 as the AssertionError said. But after "import mmselfsup", there are"UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts".

**Comment by d9j** [comment]
this project appears to be not maintained well.. it requires deprecated python 3.8 which been dropped even by anaconda.

**Comment by DeShinHwa** [comment]
Hi, did u solve it ?

**Comment by zhouzaida** [comment]
Hi, you could try to uninstall mmcv and install `mmcv==2.0.0` via `mim install mmcv==2.0.0`.

**Comment by MiXaiLL76** [comment]
https://github.com/MiXaiLL76/mmocr/commit/922bc3237cb25a52af1ccadd3542efe61f1a6ac6

Do something like this

**Comment by Yoanes-Yeo** [comment]
I've tried everything that i can, I still having the issue same like this...

**Comment by Yoanes-Yeo** [comment]
I've tried everything that i can, I still having the issue same like this... '  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects'

**Comment by DeShinHwa** [comment]
> I've tried everything that i can, I still having the issue same like this... ' ERROR: Failed building wheel for mmcv Running setup.py clean for mmcv Failed to build mmcv ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects'

If your pytorch version is 2.1.0, cuda 12.1. U can use this code below to install the specify version of the mmcv. It works for me. 
`pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html`

**Comment by MiXaiLL76** [comment]
fixed with https://github.com/open-mmlab/mmocr/pull/2023

install from git

**Comment by drzraf** [comment]
see also https://github.com/open-mmlab/mmocr/issues/2041

**Comment by amrzv** [comment]
Error still occurs in [tutorial.ipynb](https://colab.research.google.com/github/open-mmlab/mmocr/blob/master/demo/tutorial.ipynb#scrollTo=iQQIVH9ApEUv) notebook.
```python
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
```
P.S: `!mim install 'mmcv>=2.0.0rc4'` doesn't resolve the error.

**Comment by weikangqi** [comment]
so sb

**Comment by iamstarlee** [comment]
> Error still occurs in [tutorial.ipynb](https://colab.research.google.com/github/open-mmlab/mmocr/blob/master/demo/tutorial.ipynb#scrollTo=iQQIVH9ApEUv) notebook.
> 
> ```python
> AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
> ```
> 
> P.S: `!mim install 'mmcv>=2.0.0rc4'` doesn't resolve the error.

Have you solved this?

**Comment by liuwake** [comment]
mmcv==2.2.0 works fine. But you need modify the __ASSERT__ at repo `mmdetection` and `mmocr`.

```diff
diff --git a/mmocr/__init__.py b/mmocr/__init__.py
index 4524c4c3c..023a56c8a 100644
--- a/mmocr/__init__.py
+++ b/mmocr/__init__.py
@@ -13,7 +13,7 @@
 from .version import __version__, short_version
 
 mmcv_minimum_version = '2.0.0rc4'
-mmcv_maximum_version = '2.2.0'
+mmcv_maximum_version = '3.2.0'
 mmcv_version = digit_version(mmcv.__version__)
 if mmengine is not None:
     mmengine_minimum_version = '0.7.1'
```

```diff
diff --git a/mmdet/__init__.py b/mmdet/__init__.py
index 3ac884ac8b4..49589e46b26 100644
--- a/mmdet/__init__.py
+++ b/mmdet/__init__.py
@@ -6,7 +6,7 @@
 from .version import __version__, version_info
 
 mmcv_minimum_version = '2.0.0rc4'
-mmcv_maximum_version = '2.2.0'
+mmcv_maximum_version = '2.2.1'
 mmcv_version = digit_version(mmcv.__version__)
 
 mmengine_minimum_version = '0.7.1'
```

FWIW, you can install by this:
```bash
pip install numpy==1.24.4 wandb openmim
pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu118

pip install mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.4/index.html
# or mim
mim install mmcv==2.2.0

cd /kaggle/temp
git clone https://github.com/liuwake/mmdetection.git
git clone https://github.com/liuwake/mmocr.git

cd /kaggle/temp/mmdetection && pip install .
cd /kaggle/temp/mmocr && pip install .
```
